### ISSUE TITLE
Lab 01 Questions 6 and 8 Pass Wrong Parameters

### ISSUE THREAD

**Issue by jonathanfspencer** [databricks-academy/llm-foundation-models#4]
Questions 6 and 8 look to have a copy/paste error. Instead of passing in the relevant string to print the results from each question, they both pass in ```sentence```, as in:

```python
print(predict_masked_words(sentence, mlm_model, tokenizer))
```

See lines 579 & 619.

EDIT: I see that there is a [pull request](https://github.com/databricks-academy/llm-foundation-models/pull/2) for this already.

**Comment by brookewenig** [comment]
Thank you for reporting! We have just fixed this!
